site_name: CIDR Metagenomics
site_url: https://CIDR-network-hub.github.io/
repo_url: https://github.com/GSTT-CIDR/network_hub
site_author: CIDR
theme:
  name: readthedocs
  features:
    - navigation.expand

markdown_extensions:
  - sane_lists
  - attr_list
  - tables
  - admonition


plugins:
  - mermaid2
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy
            docstring_section_style: spacy
            show_source: false
  - mkdocs-pdf
  - with-pdf:
      output_path: cidr_metagenomics.pdf
      cover_subtitle: ""
      debug_html: true
      show_anchors: true
      verbose: true
  - glightbox:
      touchNavigation: true
      loop: false
  - mkdocs-video:
      is_video: True
      video_autoplay: False
      css_style:
        width: "50%"
        height: "35%"

nav:
  - Introduction: 
    - Clinical metagenomics: index.md
  - Lab Resources: 
    - Lab protocols: panmetagenomics_protocol.md
  - Bioinformatics:
    - Overview: bioinformatics_outline.md
    - Installation and validation: bioinformatics_install.md
    - Starting a MinKNOW experiment: running_minknow.md
    - Running the metagenomics workflow: running_metagenomics_workflow.md
    - Query a classification: running_organism_query.md
    - Uploading to mSCAPE: mSCAPE_integration.md
    - Summary report: additional_tools.md
    - Deployment alternatives: alternative_deployment.md
  - Analysis: 
    - Clinical evaluation SOP: clinical_interpretation.md
    - Validation outline: validation_outline.md
  - FAQ:
    - Frequently asked questions: faq.md
#    - Metagenomics sequence database: genome_database.md

site_name: "CIDR Metagenomics Hub"

extra_javascript:
  - https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js
  - https://cdn.datatables.net/2.2.2/js/dataTables.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/jvectormap/2.0.5/jquery-jvectormap.js
  - assets/js/jquery-jvectormap.js
  - assets/js/jquery-mousewheel.js
  - assets/js/jvectormap.js
  - assets/js/abstract-element.js
  - assets/js/abstract-canvas-element.js
  - assets/js/abstract-shape-element.js
  - assets/js/svg-element.js
  - assets/js/svg-group-element.js
  - assets/js/svg-canvas-element.js
  - assets/js/svg-shape-element.js
  - assets/js/svg-path-element.js
  - assets/js/svg-circle-element.js
  - assets/js/svg-image-element.js
  - assets/js/svg-text-element.js
  - assets/js/vml-element.js
  - assets/js/vml-group-element.js
  - assets/js/vml-canvas-element.js
  - assets/js/vml-shape-element.js
  - assets/js/vml-path-element.js
  - assets/js/vml-circle-element.js
  - assets/js/vml-image-element.js
  - assets/js/map-object.js
  - assets/js/region.js
  - assets/js/marker.js
  - assets/js/vector-canvas.js
  - assets/js/simple-scale.js
  - assets/js/ordinal-scale.js
  - assets/js/numeric-scale.js
  - assets/js/color-scale.js
  - assets/js/legend.js
  - assets/js/data-series.js
  - assets/js/proj.js
  - assets/js/map.js
  - assets/js/uk_mill.js

extra_css:
  - assets/js/jquery-jvectormap.css
  - https://cdn.datatables.net/2.2.2/css/dataTables.dataTables.min.css

