site_name: CIDR Metagenomics
site_url: https://CIDR-network-hub.github.io/
repo_url: https://github.com/GSTT-CIDR/network_hub
site_author: CIDR
theme:
  name: readthedocs

markdown_extensions:
  - sane_lists
  - attr_list
  - tables
  - admonition


plugins:

  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy
            docstring_section_style: spacy
            show_source: false
  - with-pdf:
      output_path: cidr_metagenomics.pdf
      cover_subtitle: ""
      debug_html: true
      show_anchors: true
      verbose: true
  - glightbox:
      touchNavigation: true
      loop: false
  - mkdocs-video:
      is_video: True
      video_autoplay: False
      css_style:
        width: "50%"
        height: "35%"

nav:
  - Introduction: index.md
  - Lab Resources: 
    - Lab protocols: panmetagenomics_protocol.md
  - Bioinformatics:
    - Outline: bioinformatics_outline.md
    - Installation: bioinformatics_install.md
    - Starting the metagenomics workflow: running_metagenomics_workflow.md
    - Query a classification: running_organism_query.md
    - Deployment alternatives: alternative_deployment.md
  - Analysis: 
    - Clinical interpretation: clinical_interpretation.md
